//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoy.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goals
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal TargetAmount { get; set; }
        public Nullable<decimal> CurrentAmount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
