//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoy.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AccountName { get; set; }
        public decimal Amount { get; set; }
        public int Type { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
